language: cpp
compiler: gcc
os:
  - linux
  - osx
osx_image: xcode9.2
dist: trusty
if: tag IS present
cache:
  directories:
    - "$TRAVIS_BUILD_DIR/dependencies"
    - "$TRAVIS_BUILD_DIR/projects"
addons:
  apt:
    packages:
      - linux-libc-dev:i386
      - gcc-4.8
      - gcc-4.8-multilib
      - g++-4.8
      - g++-4.8-multilib
install:
  - export MODULE_NAME="serversecure.core"
  - export REPOSITORY_DIR="$TRAVIS_BUILD_DIR"
  - export DEPENDENCIES="$TRAVIS_BUILD_DIR/dependencies"
  - export GARRYSMOD_COMMON="$DEPENDENCIES/garrysmod_common"
  - export SOURCE_SDK="$DEPENDENCIES/sourcesdk-minimal"
  - export TARGET_OS="$TRAVIS_OS_NAME"
  - export COMPILER_PLATFORM="gmake";
  - export BUILD_SCRIPT="$GARRYSMOD_COMMON/build/ci.sh"
  - export GARRYSMOD_COMMON_REPOSITORY="https://github.com/danielga/garrysmod_common.git"
  - export PREMAKE5_EXECUTABLE="premake5";
  - if [ $TRAVIS_OS_NAME = "osx" ]; then
      export PREMAKE5="$DEPENDENCIES/macosx/premake-core/premake5";
      export PROJECT_OS="macosx";
      export CXX="g++";
      export CC="gcc";
    elif [ $TRAVIS_OS_NAME = "linux" ]; then
      export PREMAKE5="$DEPENDENCIES/linux/premake-core/premake5";
      export PROJECT_OS="linux";
      export CXX="g++-4.8";
      export CC="gcc-4.8";
    fi
  - mkdir -p "$DEPENDENCIES"
  - if [ ! -f "$GARRYSMOD_COMMON/premake5.lua" ]; then
      echo "garrysmod_common directory is empty, doing git clone of the remote repo";
      git clone --recursive "$GARRYSMOD_COMMON_REPOSITORY" "$GARRYSMOD_COMMON";
    else
      echo "garrysmod_common directory is good, pulling any latest changes";
      git -C "$GARRYSMOD_COMMON" pull;
      git -C "$GARRYSMOD_COMMON" submodule update --init --recursive;
    fi
script: "$BUILD_SCRIPT"
deploy:
  provider: releases
  skip_cleanup: true
  file: "${TRAVIS_BUILD_DIR}/projects/${PROJECT_OS}/${COMPILER_PLATFORM}/release/gmsv_${MODULE_NAME}_${TARGET_OS}.dll"
  on:
    tags: true
  api_key:
    secure: DMW0byGslhkzT3m4xgGHPIg8IsbmgfdDvwhyiDOyssftqcZnddl7Yit1IS/4q/StMeagWrCF+cbYee0n1v5QtOUu3Cr5EXBFgzwHmvYdTGHuEbMwcR/uM5R6UzgXpNn363mWiyYP5txuA2dX8DPULMZU/BCCxH9/Uuk6nNC8KfoSTAjYQTRt+VToNVEBKcZJ/VWlP2LWketQyY83r0OFnwbXihpw+Z/WAmt3FUfvtrAdBnOi3vxHCoib6RvHcUp4FLIrLEkmAjrFwrhKn/miPWWpCmh+Ou4YXSVuE5Wzj+zNY/6XpS4l4VDVu5zgu4T0RsYxS/9f9QoYPTo19By9NcWgXY9kdUcxAoRSv9JIPE4779a7THrXvnlrRu1B+wo9NAnxjK2rTmdFlLQrqR8uaSXKgTOyRlFHao5/AX82vss44XcWqM8dNQk8tjc4uwb9n1WAnDIKJ9KBKCD5EmfeVMTPEuGfIQJmHcNc/VLzBiD8rrLDP+w4zcK5QqLNr3jqes0u/OJz+XFAehkmIs6rt9Lt8D66h2hgu/OYwsdIc/1ZvyySZrVzcSzmGlgQbwQheXPlFcdQncvQH87LQmj48Vj49tPbwWcmiAd/3tHNSS1ZcNc2VrMSNEJZ0lS2zgg+0i7FBYYAC9vbQAtxN7MI+6SwL4en5DjVHW3AKRlTTIw=
